# DATASETS
datasets:
  zipf_small:
    distribution: zipf
    n: 20
    file_number: 3
    seed: 123
    param: 1.1
    
# INSTANCES (ALGORITHMS WITH SPECIFIED PARAMETERS)
instances:
  misra_k_10:
    binary: misra-gries
    params: [5]
    
    
# EXPERIMENTS (DETERMINED BY DATASETS AND INSTANCES) 
# Parameter k is for metrics only
experiments:
  hello_world:
    instances: [misra_k_10]
    datasets: [zipf_small]
    seeds: [10, 11]
    k: 5
